### ISSUE TITLE
Add the 'get involved' blurb automatically to blog posts

### ISSUE THREAD

**Issue by JoblersTune** [interledger/interledger.org-developers#100]
Every blog post needs to end with a standard paragraph

> As we are open source, you can easily check our work on [GitHub](https://github.com/interledger/). If the work mentioned here inspired you, we welcome your contributions. You can join our [community slack](https://communityinviter.com/apps/interledger/interledger-working-groups-slack) or participate in the next [community call](https://docs.google.com/document/u/1/d/1T_Q_eRZtL8GluJR9rVADd7fvkB8mPluMk-d96LM4vlg/edit#heading=h.ybdhwl6k5886), which takes place each second Wednesday of the month.
> 
> If you want to stay updated with all open opportunities and news from the Interledger Foundation, you can subscribe to our [newsletter](https://interledger.org/subscribe).

Instead of relying on everyone remembering individually, this should be automated, or embedded directly, or at very least part of the blog template Google Doc.

**Comment by huijing** [comment]
Resolved by https://github.com/interledger/interledger.org-developers/pull/105
